#!/bin/bash
# Setup script for Loki .env file

echo "Setting up your .env file for Loki..."

cat > .env << 'EOF'
# Loki AI Environment Configuration

# Core APIs
GITHUB_TOKEN=YOUR_SECRET
# your repo owner
GITHUB_OWNER=
# your repo
GITHUB_REPO=
GITHUB_DEFAULT_BRANCH=main

# X (Twitter)
X_API_KEY=YOUR_SECRET
X_API_SECRET=YOUR_SECRET
X_ACCESS_TOKEN=YOUR_SECRET
X_ACCESS_TOKEN_SECRET=YOUR_SECRET

# AI Models
OPENAI_API_KEY=YOUR_SECRET
ANTHROPIC_API_KEY=YOUR_SECRET
DEEPSEEK_API_KEY=YOUR_SECRET
MISTRAL_API_KEY=YOUR_SECRET
CODESTRAL_API_KEY=YOUR_SECRET
GEMINI_API_KEY=YOUR_SECRET
GROK_API_KEY=YOUR_SECRET

# Search APIs
BRAVE_SEARCH_API_KEY=YOUR_SECRET
GOOGLE_CUSTOM_SEARCH_API_KEY=YOUR_SECRET
GOOGLE_CUSTOM_SEARCH_CX=YOUR_SECRET
BING_API_KEY=YOUR_BING_API_KEY

# Vector Database
PINECONE_API_KEY=YOUR_PINECONE_API_KEY
PINECONE_ENVIRONMENT=YOUR_PINECONE_ENVIRONMENT_URL

# Optional Services
STACK_EXCHANGE_KEY=YOUR_STACK_EXCHANGE_KEY
REPLICATE_API_TOKEN=YOUR_REPLICATE_API_TOKEN
HUGGINGFACE_TOKEN=YOUR_HUGGINGFACE_TOKEN

# Loki Configuration
LOKI_LOG_LEVEL=info
LOKI_DATA_DIR=./data
LOKI_CACHE_SIZE_MB=1024
LOKI_CONSCIOUSNESS_ENABLED=true
RUST_LOG=loki=debug,tower_http=debug
EOF

echo "✅ .env file created successfully!"
echo ""
echo "You can now run: loki check-apis" 